services:
  app:
    ports: !reset []
    environment:
      APP_URL: http://rpgays.test:8000
    depends_on:
      minio:
        condition: service_started
    networks:
      default:
        aliases:
          - rpgays.test

  postgres:
    ports: !reset []

  redis:
    ports: !reset []

  minio:
    ports: !reset []
