<?php

declare(strict_types=1);

use App\Http\Controllers\Api\ControlAssetController;
use App\Http\Controllers\Api\ControlAudioCueController;
use App\Http\Controllers\Api\ControlAuthenticationController;
use App\Http\Controllers\Api\ControlCampaignController;
use App\Http\Controllers\Api\ControlCampaignMapController;
use App\Http\Controllers\Api\ControlDicePresetController;
use App\Http\Controllers\Api\ControlLiveSessionController;
use App\Http\Controllers\Api\ControlMapProgressController;
use App\Http\Controllers\Api\ControlNpcController;
use App\Http\Controllers\Api\ControlNpcNoteController;
use App\Http\Controllers\Api\ControlNpcRevealController;
use App\Http\Controllers\Api\ControlOverlayStateController;
use App\Http\Controllers\Api\ControlPlayerCharacterController;
use App\Http\Controllers\Api\ControlPlayerMapStateController;
use App\Http\Controllers\Api\ControlPresentationStateController;
use App\Http\Controllers\Api\ControlRealtimeStatusController;
use App\Http\Controllers\Api\ControlSceneController;
use App\Http\Controllers\Api\ControlSessionParticipantController;
use App\Http\Controllers\Api\ControlSessionPlayerGroupController;
use App\Http\Controllers\Api\ControlStagePresetController;
use App\Http\Controllers\Api\ControlVideoCueController;
use App\Http\Controllers\Api\ParticipantClaimController;
use App\Http\Controllers\Api\ParticipantMapAssetController;
use App\Http\Controllers\Api\ParticipantMapProgressController;
use App\Http\Controllers\Api\ParticipantNpcController;
use App\Http\Controllers\Api\ParticipantNpcNoteController;
use App\Http\Controllers\Api\ParticipantPlayerGroupController;
use App\Http\Controllers\Api\ParticipantRosterController;
use App\Http\Controllers\Api\ParticipantSessionController;
use App\Http\Controllers\Api\PresentationAssetController;
use App\Http\Controllers\Api\PresentationOverlayStateController;
use App\Http\Controllers\Api\PresentationPairingController;
use App\Http\Controllers\Api\PresentationRenderController;
use App\Http\Controllers\Api\PresentationSfxController;
use App\Http\Controllers\Api\PresentationStandbyController;
use App\Http\Controllers\Api\PresentationStateController;
use App\Http\Controllers\Api\PresentationVideoController;
use Illuminate\Support\Facades\Route;

Route::middleware(['web'])->prefix('control/v1')->group(function (): void {
    Route::get('auth', [ControlAuthenticationController::class, 'show']);
    Route::post('auth/login', [ControlAuthenticationController::class, 'login'])->middleware('throttle:control-login');
    Route::post('auth/logout', [ControlAuthenticationController::class, 'logout'])->middleware('control');

    Route::middleware('control')->group(function (): void {
        Route::get('campaigns', [ControlCampaignController::class, 'index']);
        Route::post('campaigns', [ControlCampaignController::class, 'store']);
        Route::post('campaigns/import', [ControlCampaignController::class, 'import']);
        Route::get('campaigns/{campaign}/revisions', [ControlCampaignController::class, 'revisions']);
        Route::get('campaigns/{campaign}/revisions/{revision}', [ControlCampaignController::class, 'revision']);
        Route::get('campaigns/{campaign}/revisions/{revision}/package', [ControlCampaignController::class, 'exportRevision']);
        Route::get('campaigns/{campaign}/sessions', [ControlLiveSessionController::class, 'index']);
        Route::post('campaigns/{campaign}/sessions', [ControlLiveSessionController::class, 'store']);
        Route::get('campaigns/{campaign}/sessions/{session}/player-map', [ControlPlayerMapStateController::class, 'show']);
        Route::put('campaigns/{campaign}/sessions/{session}/player-map', [ControlPlayerMapStateController::class, 'update']);
        Route::get('realtime/status', [ControlRealtimeStatusController::class, 'show']);
        Route::get('campaigns/{campaign}/sessions/{session}/presentation-state', [ControlPresentationStateController::class, 'show']);
        Route::put('campaigns/{campaign}/sessions/{session}/presentation-state', [ControlPresentationStateController::class, 'update']);
        Route::post('campaigns/{campaign}/sessions/{session}/presentation-state/standby', [ControlPresentationStateController::class, 'standby']);
        Route::post('campaigns/{campaign}/sessions/{session}/presentation-state/go', [ControlPresentationStateController::class, 'go']);
        Route::get('campaigns/{campaign}/sessions/{session}/overlays', [ControlOverlayStateController::class, 'show']);
        Route::post('campaigns/{campaign}/sessions/{session}/overlays', [ControlOverlayStateController::class, 'enqueue']);
        Route::patch('campaigns/{campaign}/sessions/{session}/overlays/{overlay}', [ControlOverlayStateController::class, 'update']);
        Route::post('campaigns/{campaign}/sessions/{session}/overlays/{lane}/advance', [ControlOverlayStateController::class, 'advance']);
        Route::post('campaigns/{campaign}/sessions/{session}/overlays/{lane}/dismiss', [ControlOverlayStateController::class, 'dismiss']);
        Route::get('campaigns/{campaign}/sessions/{session}/maps/{map}/progress', [ControlMapProgressController::class, 'show']);
        Route::put('campaigns/{campaign}/sessions/{session}/maps/{map}/progress', [ControlMapProgressController::class, 'update']);
        Route::post('campaigns/{campaign}/sessions/{session}/maps/{map}/progress/reset', [ControlMapProgressController::class, 'reset']);
        Route::post('campaigns/{campaign}/sessions/{session}/maps/{map}/progress/fog', [ControlMapProgressController::class, 'brush']);
        Route::get('campaigns/{campaign}/sessions/{session}/revisions/{revision}/preflight', [ControlLiveSessionController::class, 'preflight']);
        Route::post('campaigns/{campaign}/sessions/{session}/adopt-revision', [ControlLiveSessionController::class, 'adopt']);
        Route::get('campaigns/{campaign}/sessions/{session}/participants', [ControlSessionParticipantController::class, 'index']);
        Route::delete('campaigns/{campaign}/sessions/{session}/participants/{participant}/claim', [ControlSessionParticipantController::class, 'release']);
        Route::delete('campaigns/{campaign}/sessions/{session}/participants/{participant}', [ControlSessionParticipantController::class, 'revoke']);
        Route::get('campaigns/{campaign}/sessions/{session}/player-groups', [ControlSessionPlayerGroupController::class, 'index']);
        Route::post('campaigns/{campaign}/sessions/{session}/player-groups', [ControlSessionPlayerGroupController::class, 'store']);
        Route::put('campaigns/{campaign}/sessions/{session}/player-groups/{group}/members/{participant}', [ControlSessionPlayerGroupController::class, 'addMember']);
        Route::delete('campaigns/{campaign}/sessions/{session}/player-groups/{group}/members/{participant}', [ControlSessionPlayerGroupController::class, 'removeMember']);
        Route::get('campaigns/{campaign}/sessions/{session}/npc-reveals', [ControlNpcRevealController::class, 'index']);
        Route::put('campaigns/{campaign}/sessions/{session}/npc-reveals/{npc}', [ControlNpcRevealController::class, 'update']);
        Route::get('campaigns/{campaign}/sessions/{session}/npc-notes', [ControlNpcNoteController::class, 'index']);
        Route::patch('campaigns/{campaign}/sessions/{session}/npc-notes/{note}', [ControlNpcNoteController::class, 'update']);
        Route::delete('campaigns/{campaign}/sessions/{session}/npc-notes/{note}', [ControlNpcNoteController::class, 'destroy']);
        Route::get('campaigns/{campaign}/assets', [ControlAssetController::class, 'index']);
        Route::get('campaigns/{campaign}/audio-cues', [ControlAudioCueController::class, 'index']);
        Route::post('campaigns/{campaign}/audio-cues', [ControlAudioCueController::class, 'store']);
        Route::get('campaigns/{campaign}/video-cues', [ControlVideoCueController::class, 'index']);
        Route::post('campaigns/{campaign}/video-cues', [ControlVideoCueController::class, 'store']);
        Route::get('campaigns/{campaign}/dice-presets', [ControlDicePresetController::class, 'index']);
        Route::post('campaigns/{campaign}/dice-presets', [ControlDicePresetController::class, 'store']);
        Route::get('campaigns/{campaign}/scenes', [ControlSceneController::class, 'index']);
        Route::post('campaigns/{campaign}/scenes', [ControlSceneController::class, 'store']);
        Route::get('campaigns/{campaign}/scenes/{scene}/backdrops', [ControlSceneController::class, 'backdrops']);
        Route::post('campaigns/{campaign}/scenes/{scene}/backdrops', [ControlSceneController::class, 'storeBackdrop']);
        Route::get('campaigns/{campaign}/stage-presets', [ControlStagePresetController::class, 'index']);
        Route::post('campaigns/{campaign}/stage-presets', [ControlStagePresetController::class, 'store']);
        Route::get('campaigns/{campaign}/stage-presets/{stagePreset}/entries', [ControlStagePresetController::class, 'entries']);
        Route::post('campaigns/{campaign}/stage-presets/{stagePreset}/entries', [ControlStagePresetController::class, 'storeEntry']);
        Route::get('campaigns/{campaign}/maps', [ControlCampaignMapController::class, 'index']);
        Route::post('campaigns/{campaign}/maps', [ControlCampaignMapController::class, 'store']);
        Route::get('campaigns/{campaign}/maps/{map}/fog-mask', [ControlCampaignMapController::class, 'fogMask']);
        Route::put('campaigns/{campaign}/maps/{map}/fog-mask', [ControlCampaignMapController::class, 'setFogMask']);
        Route::get('campaigns/{campaign}/maps/{map}/tokens', [ControlCampaignMapController::class, 'tokens']);
        Route::post('campaigns/{campaign}/maps/{map}/tokens', [ControlCampaignMapController::class, 'storeToken']);
        Route::get('campaigns/{campaign}/player-characters', [ControlPlayerCharacterController::class, 'index']);
        Route::post('campaigns/{campaign}/player-characters', [ControlPlayerCharacterController::class, 'store']);
        Route::get('campaigns/{campaign}/npcs', [ControlNpcController::class, 'index']);
        Route::post('campaigns/{campaign}/npcs', [ControlNpcController::class, 'store']);
        Route::get('campaigns/{campaign}/npcs/{npc}/states', [ControlNpcController::class, 'states']);
        Route::post('campaigns/{campaign}/npcs/{npc}/states', [ControlNpcController::class, 'storeState']);
        Route::post('campaigns/{campaign}/assets/uploads', [ControlAssetController::class, 'initiate']);
        Route::post('campaigns/{campaign}/assets/{asset}/complete', [ControlAssetController::class, 'complete']);
        Route::get('campaigns/{campaign}/assets/{asset}/read', [ControlAssetController::class, 'read']);
        Route::patch('campaigns/{campaign}', [ControlCampaignController::class, 'update']);
        Route::post('campaigns/{campaign}/publish', [ControlCampaignController::class, 'publish']);
        Route::delete('campaigns/{campaign}', [ControlCampaignController::class, 'destroy']);
    });
});

Route::middleware(['web'])->prefix('presentation/v1')->group(function (): void {
    Route::post('pair', [PresentationPairingController::class, 'pair']);
    Route::get('state', [PresentationStateController::class, 'show']);
    Route::get('render', [PresentationRenderController::class, 'show']);
    Route::get('assets/{asset}/read', [PresentationAssetController::class, 'read']);
    Route::post('standby/report', [PresentationStandbyController::class, 'report']);
    Route::post('video/complete', [PresentationVideoController::class, 'complete']);
    Route::post('video/fail', [PresentationVideoController::class, 'fail']);
    Route::post('sfx/complete', [PresentationSfxController::class, 'complete']);
    Route::get('overlays', [PresentationOverlayStateController::class, 'show']);
});

Route::middleware(['web'])->prefix('participant/v1')->group(function (): void {
    Route::post('join', [ParticipantSessionController::class, 'join']);
    Route::post('resume', [ParticipantSessionController::class, 'resume']);
    Route::get('roster', [ParticipantRosterController::class, 'index']);
    Route::get('player-groups', [ParticipantPlayerGroupController::class, 'index']);
    Route::post('claim', [ParticipantClaimController::class, 'claim']);
    Route::get('npcs', [ParticipantNpcController::class, 'index']);
    Route::post('npcs/{npc}/notes', [ParticipantNpcNoteController::class, 'store']);
    Route::patch('npc-notes/{note}', [ParticipantNpcNoteController::class, 'update']);
    Route::delete('npc-notes/{note}', [ParticipantNpcNoteController::class, 'destroy']);
    Route::get('map', [ParticipantMapProgressController::class, 'current']);
    Route::get('map/assets/{asset}/read', [ParticipantMapAssetController::class, 'read']);
    Route::get('maps/{map}/progress', [ParticipantMapProgressController::class, 'show']);
});
