import { computed, createApp, defineComponent, onBeforeUnmount, onMounted, ref } from 'vue';
import { createPinia } from 'pinia';
import { createRouter, createWebHistory, useRoute, useRouter } from 'vue-router';
import { api, ApiError } from '../shared/api';
import { useRealtimeSnapshot } from '../shared/realtime';
import { ControlMapStage } from '../shared/control-map-stage';
import { PresentationStage, type PresentationStageEntry } from '../shared/presentation-stage';
import VueKonva from 'vue-konva';
import '../css/app.css';

type Campaign = {
    id: string;
    name: string;
    draft_revision: number;
    archived_at: string | null;
    updated_at: string;
};

type ApiResponse<T> = { data: T; meta?: { replayed: boolean } };
type Asset = { id: string; original_filename: string; kind: string; declared_mime: string; byte_size: number; upload_status: string; validation_error: string | null };
type PlayerCharacter = { id: string; name: string; pronouns: string | null; public_description: string | null; avatar_asset_id: string | null };
type Npc = { id: string; name: string; pronouns: string | null; public_description: string | null; normal_asset_id: string; native_facing: 'left' | 'right' };
type NpcState = { id: string; name: string; asset_id: string; sort_order: number };
type AudioCue = { id: string; name: string; asset_id: string; kind: 'music' | 'sfx'; loop: boolean; default_volume: number };
type VideoCue = { id: string; name: string; primary_asset_id: string; fallback_asset_id: string | null; completion_mode: 'restore_captured_scene' | 'enter_target_scene'; target_scene_id: string | null; music_during: 'continue' | 'pause' | 'stop'; music_after: 'keep_current' | 'resume_prior' | 'start_target_default' | 'remain_silent'; embedded_audio_volume: number; embedded_audio_muted: boolean };
type SceneRecord = { id: string; name: string; primary_backdrop_asset_id: string | null; default_music_cue_id: string | null; base_stage_preset_id: string | null; transition: 'cut' | 'fade_black' | 'cross_dissolve'; transition_duration_ms: number };
type StagePresetRecord = { id: string; name: string; tween_duration_ms: number; tween_easing: string };
type DicePresetRecord = { id: string; name: string; expression: string; default_visibility: 'public' | 'private'; is_default: boolean };
type CampaignRevision = { id: string; number: number; published_at: string };
type LiveSessionRecord = { id: string; campaign_revision_id: string; progress_mode: 'fresh' | 'resume'; player_code: string; status: string; created_at: string; display_pairing_token?: string };
type SessionParticipantRecord = { id: string; role: 'player' | 'spectator'; display_name: string; player_character_id: string | null; revoked_at: string | null };
type SessionNpcRevealRecord = { id: string; npc_id: string; is_revealed: boolean; revealed_at: string | null };
type PinnedMap = { id: string; name: string; image_asset_id: string };
type PlayerMapState = { map_id: string | null; revision: number };
type MapToken = { source_token_id: string; label: string | null; position_x: number; position_y: number; scale: number; sort_order: number };
type MapProgress = { revision: number; tokens: MapToken[]; fog: { default_visibility: string; brushes: unknown[] } };
type PresentationStateEntry = { npc_id: string; npc_state_id: string | null; position_x: number; position_y: number; scale: number; layer_order: number; facing: 'left' | 'right' };
type MusicPlayback = { status: 'playing' | 'paused' | 'stopped'; position_seconds: number; position_command_id: string | null; loop: boolean; volume: number; fade_duration_ms: number };
type SfxInstance = { id: string; cue_id: string; loop: boolean; volume: number };
type PresentationCue = { scene_id: string | null; backdrop_asset_id: string | null; music_cue_id: string | null; music_playback: MusicPlayback; sfx_master_volume: number; sfx_instances: SfxInstance[]; video_cue_id: string | null; stage_preset_id: string | null; stage_entries: PresentationStateEntry[] };
type PresentationSnapshot = { revision: number; state: PresentationCue & { standby: PresentationCue | null; standby_status: 'idle' | 'preparing' | 'ready' | 'error'; standby_error: string | null } };
type PinnedScene = { id: string; name: string; primary_backdrop_asset_id: string | null; default_music_cue_id: string | null; base_stage_preset_id: string | null; transition: 'cut' | 'fade_black' | 'cross_dissolve'; transition_duration_ms: number };
type PinnedNpc = { id: string; name: string; normal_asset_id: string; native_facing: 'left' | 'right' };
type PinnedNpcState = { id: string; npc_id: string; asset_id: string; name: string };
type PinnedStagePresetEntry = PresentationStateEntry & { stage_preset_id: string };
type PinnedStagePreset = { id: string; name: string; tween_duration_ms: number; tween_easing: 'linear' | 'ease_in' | 'ease_out' | 'ease_in_out' };
type PinnedSceneBackdrop = { id: string; scene_id: string; asset_id: string; name: string };
type PinnedAudioCue = { id: string; name: string; kind: 'music' | 'sfx'; loop: boolean; default_volume: number };
type PinnedVideoCue = { id: string; name: string; completion_mode: 'restore_captured_scene' | 'enter_target_scene'; music_during: 'continue' | 'pause' | 'stop'; music_after: 'keep_current' | 'resume_prior' | 'start_target_default' | 'remain_silent' };

const commandId = (): string => crypto.randomUUID();

const LoginView = defineComponent({
    setup() {
        const router = useRouter();
        const secret = ref('');
        const error = ref('');
        const pending = ref(false);

        const login = async (): Promise<void> => {
            pending.value = true;
            error.value = '';
            try {
                await api<ApiResponse<{ authenticated: boolean }>>('/api/control/v1/auth/login', {
                    method: 'POST', body: JSON.stringify({ secret: secret.value }),
                });
                await router.replace('/');
            } catch (reason) {
                error.value = reason instanceof ApiError ? reason.message : 'Unable to contact Control.';
            } finally {
                pending.value = false;
            }
        };

        return { secret, error, pending, login };
    },
    template: `
        <main class="shell"><section class="panel stack" aria-labelledby="control-login-title">
            <div><div class="eyebrow">Theatrical RPG</div><h1 id="control-login-title">Control</h1></div>
            <p class="muted">Enter the environment-held Control secret to manage campaign drafts.</p>
            <p v-if="error" class="error" role="alert">{{ error }}</p>
            <form class="stack" @submit.prevent="login">
                <label for="control-secret">Control secret</label>
                <input id="control-secret" v-model="secret" type="password" autocomplete="current-password" required autofocus>
                <button :disabled="pending">{{ pending ? 'Signing in…' : 'Sign in' }}</button>
            </form>
        </section></main>`,
});

const CampaignsView = defineComponent({
    setup() {
        const router = useRouter();
        const campaigns = ref<Campaign[]>([]);
        const campaignName = ref('');
        const error = ref('');
        const busy = ref(false);

        const load = async (): Promise<void> => {
            try {
                campaigns.value = (await api<ApiResponse<Campaign[]>>('/api/control/v1/campaigns')).data;
            } catch (reason) {
                if (reason instanceof ApiError && reason.status === 401) await router.replace('/login');
                else error.value = reason instanceof Error ? reason.message : 'Unable to load campaigns.';
            }
        };

        const createCampaign = async (): Promise<void> => {
            if (!campaignName.value.trim()) return;
            busy.value = true;
            error.value = '';
            try {
                const response = await api<ApiResponse<Campaign>>('/api/control/v1/campaigns', {
                    method: 'POST', body: JSON.stringify({ command_id: commandId(), name: campaignName.value }),
                });
                campaigns.value = [...campaigns.value, response.data].sort((a, b) => a.name.localeCompare(b.name));
                campaignName.value = '';
            } catch (reason) {
                error.value = reason instanceof Error ? reason.message : 'Unable to create campaign.';
            } finally { busy.value = false; }
        };

        const rename = async (campaign: Campaign): Promise<void> => {
            try {
                const response = await api<ApiResponse<Campaign>>(`/api/control/v1/campaigns/${campaign.id}`, {
                    method: 'PATCH', body: JSON.stringify({ command_id: commandId(), expected_revision: campaign.draft_revision, name: campaign.name }),
                });
                Object.assign(campaign, response.data);
            } catch (reason) {
                error.value = reason instanceof ApiError && reason.status === 409
                    ? 'This campaign changed elsewhere. The current state has been reloaded.'
                    : reason instanceof Error ? reason.message : 'Unable to rename campaign.';
                await load();
            }
        };

        const archive = async (campaign: Campaign): Promise<void> => {
            if (!window.confirm(`Archive “${campaign.name}”?`)) return;
            try {
                await api<ApiResponse<Campaign>>(`/api/control/v1/campaigns/${campaign.id}`, {
                    method: 'DELETE', body: JSON.stringify({ command_id: commandId(), expected_revision: campaign.draft_revision }),
                });
                campaigns.value = campaigns.value.filter(({ id }) => id !== campaign.id);
            } catch (reason) {
                error.value = reason instanceof Error ? reason.message : 'Unable to archive campaign.';
                await load();
            }
        };

        const logout = async (): Promise<void> => {
            await api<void>('/api/control/v1/auth/logout', { method: 'POST', body: JSON.stringify({}) });
            await router.replace('/login');
        };

        const realtime = useRealtimeSnapshot({ load: async () => { await load(); return campaigns.value; }, channel: () => 'control.campaigns' });
        onMounted(() => void realtime.start());
        onBeforeUnmount(realtime.stop);
        return { campaigns, campaignName, error, busy, createCampaign, rename, archive, logout, realtimeStatus: realtime.status };
    },
    template: `
        <main class="shell stack"><header class="row"><div><div class="eyebrow">Theatrical RPG</div><h1>Campaign drafts</h1><p class="muted" role="status">Realtime: {{ realtimeStatus === 'live' ? 'live' : realtimeStatus === 'degraded' ? 'degraded — polling snapshots' : 'connecting' }}</p></div><button class="secondary" @click="logout">Sign out</button></header>
            <section class="panel stack" aria-labelledby="new-campaign-title"><h2 id="new-campaign-title">New campaign</h2>
                <form class="row" @submit.prevent="createCampaign"><input v-model="campaignName" aria-label="Campaign name" maxlength="120" required placeholder="Campaign name"><button :disabled="busy">Create campaign</button></form>
            </section>
            <p v-if="error" class="error" role="alert">{{ error }}</p>
            <section class="panel stack" aria-labelledby="campaign-list-title"><h2 id="campaign-list-title">Active drafts</h2>
                <p v-if="campaigns.length === 0" class="muted">No campaign drafts yet.</p>
                <article v-for="campaign in campaigns" :key="campaign.id" class="campaign"><input v-model="campaign.name" :aria-label="'Name for ' + campaign.name" maxlength="120"><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/assets', query: { revision: campaign.draft_revision } }">Assets</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/pcs', query: { revision: campaign.draft_revision } }">PCs</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/npcs', query: { revision: campaign.draft_revision } }">NPCs</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/audio', query: { revision: campaign.draft_revision } }">Audio</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/video', query: { revision: campaign.draft_revision } }">Video</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/scenes', query: { revision: campaign.draft_revision } }">Scenes</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/dice', query: { revision: campaign.draft_revision } }">Dice</RouterLink><RouterLink class="button secondary" :to="{ path: '/campaigns/' + campaign.id + '/sessions' }">Sessions</RouterLink><button class="secondary" @click="rename(campaign)">Save</button><button class="danger" @click="archive(campaign)">Archive</button></article>
            </section>
        </main>`,
});

const PlayerCharactersView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter(); const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const characters = ref<PlayerCharacter[]>([]); const assets = ref<Asset[]>([]); const name = ref(''); const pronouns = ref(''); const description = ref(''); const avatar = ref(''); const error = ref(''); const busy = ref(false);
        const load = async (): Promise<void> => { try { const [pcs, media] = await Promise.all([api<ApiResponse<PlayerCharacter[]>>(`/api/control/v1/campaigns/${id}/player-characters`), api<ApiResponse<Asset[]>>(`/api/control/v1/campaigns/${id}/assets`)]); characters.value = pcs.data; assets.value = media.data.filter((asset) => asset.kind === 'image' && asset.upload_status === 'ready'); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load characters.'; } };
        const create = async (): Promise<void> => { if (!name.value.trim()) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<PlayerCharacter>>(`/api/control/v1/campaigns/${id}/player-characters`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: name.value, pronouns: pronouns.value || null, public_description: description.value || null, avatar_asset_id: avatar.value || null }) }); characters.value = [...characters.value, response.data]; revision.value++; name.value = ''; pronouns.value = ''; description.value = ''; avatar.value = ''; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this PC.'; await load(); } finally { busy.value = false; } };
        onMounted(load); return { characters, assets, name, pronouns, description, avatar, error, busy, create, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>Player characters</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Add player character</h2><input v-model="name" maxlength="120" required placeholder="Character name" aria-label="Character name"><input v-model="pronouns" maxlength="120" placeholder="Pronouns" aria-label="Pronouns"><input v-model="description" maxlength="500" placeholder="Short public description" aria-label="Public description"><select v-model="avatar" aria-label="Avatar image"><option value="">No avatar</option><option v-for="asset in assets" :key="asset.id" :value="asset.id">{{ asset.original_filename }}</option></select><button :disabled="busy" @click="create">{{ busy ? 'Creating…' : 'Create PC' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Draft roster</h2><p v-if="characters.length === 0" class="muted">No player characters yet.</p><article v-for="character in characters" :key="character.id" class="asset"><div><strong>{{ character.name }}</strong><div class="muted">{{ character.pronouns || 'Pronouns not set' }}</div><div class="muted">{{ character.public_description }}</div></div></article></section></main>`,
});

const NpcsView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter(); const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const npcs = ref<Npc[]>([]); const assets = ref<Asset[]>([]); const states = ref<NpcState[]>([]); const name = ref(''); const pronouns = ref(''); const description = ref(''); const normal = ref(''); const facing = ref<'left' | 'right'>('right'); const selected = ref(''); const stateName = ref(''); const stateAsset = ref(''); const error = ref(''); const busy = ref(false);
        const loadStates = async (): Promise<void> => { if (!selected.value) { states.value = []; return; } states.value = (await api<ApiResponse<NpcState[]>>(`/api/control/v1/campaigns/${id}/npcs/${selected.value}/states`)).data; };
        const load = async (): Promise<void> => { try { const [characters, media] = await Promise.all([api<ApiResponse<Npc[]>>(`/api/control/v1/campaigns/${id}/npcs`), api<ApiResponse<Asset[]>>(`/api/control/v1/campaigns/${id}/assets`)]); npcs.value = characters.data; assets.value = media.data.filter((asset) => asset.kind === 'image' && asset.upload_status === 'ready'); if (selected.value) await loadStates(); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load NPCs.'; } };
        const create = async (): Promise<void> => { if (!name.value.trim() || !normal.value) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<Npc>>(`/api/control/v1/campaigns/${id}/npcs`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: name.value, pronouns: pronouns.value || null, public_description: description.value || null, normal_asset_id: normal.value, native_facing: facing.value }) }); npcs.value = [...npcs.value, response.data]; revision.value++; name.value = ''; pronouns.value = ''; description.value = ''; normal.value = ''; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this NPC.'; await load(); } finally { busy.value = false; } };
        const addState = async (): Promise<void> => { if (!selected.value || !stateName.value.trim() || !stateAsset.value) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<NpcState>>(`/api/control/v1/campaigns/${id}/npcs/${selected.value}/states`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: stateName.value, asset_id: stateAsset.value }) }); states.value = [...states.value, response.data]; revision.value++; stateName.value = ''; stateAsset.value = ''; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to add this state.'; await loadStates(); } finally { busy.value = false; } };
        onMounted(load); return { npcs, assets, states, name, pronouns, description, normal, facing, selected, stateName, stateAsset, error, busy, create, addState, loadStates, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>NPCs</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Add NPC</h2><input v-model="name" maxlength="120" required placeholder="NPC name" aria-label="NPC name"><input v-model="pronouns" maxlength="120" placeholder="Pronouns" aria-label="NPC pronouns"><input v-model="description" maxlength="500" placeholder="Short public description" aria-label="NPC description"><select v-model="normal" aria-label="Normal portrait"><option value="">Choose normal portrait</option><option v-for="asset in assets" :key="asset.id" :value="asset.id">{{ asset.original_filename }}</option></select><select v-model="facing" aria-label="Native facing"><option value="right">Faces right</option><option value="left">Faces left</option></select><button :disabled="busy" @click="create">{{ busy ? 'Creating…' : 'Create NPC' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Optional emotional states</h2><select v-model="selected" aria-label="NPC for states" @change="loadStates"><option value="">Choose NPC</option><option v-for="npc in npcs" :key="npc.id" :value="npc.id">{{ npc.name }}</option></select><input v-model="stateName" maxlength="120" placeholder="State name" aria-label="State name"><select v-model="stateAsset" aria-label="State image"><option value="">Choose state image</option><option v-for="asset in assets" :key="asset.id" :value="asset.id">{{ asset.original_filename }}</option></select><button :disabled="busy || !selected" @click="addState">Add state</button><p v-if="selected && states.length === 0" class="muted">No states for this NPC.</p><article v-for="state in states" :key="state.id" class="asset"><strong>{{ state.name }}</strong></article></section><section class="panel stack"><h2>Draft NPCs</h2><p v-if="npcs.length === 0" class="muted">No NPCs yet.</p><article v-for="npc in npcs" :key="npc.id" class="asset"><div><strong>{{ npc.name }}</strong><div class="muted">Faces {{ npc.native_facing }} · {{ npc.pronouns || 'Pronouns not set' }}</div><div class="muted">{{ npc.public_description }}</div></div></article></section></main>`,
});

const AudioCuesView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter(); const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const cues = ref<AudioCue[]>([]); const assets = ref<Asset[]>([]); const name = ref(''); const asset = ref(''); const kind = ref<'music' | 'sfx'>('music'); const loop = ref(false); const volume = ref(100); const error = ref(''); const busy = ref(false);
        const load = async (): Promise<void> => { try { const [audio, media] = await Promise.all([api<ApiResponse<AudioCue[]>>(`/api/control/v1/campaigns/${id}/audio-cues`), api<ApiResponse<Asset[]>>(`/api/control/v1/campaigns/${id}/assets`)]); cues.value = audio.data; assets.value = media.data.filter((item) => item.kind === 'audio' && item.upload_status === 'ready'); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load audio cues.'; } };
        const create = async (): Promise<void> => { if (!name.value.trim() || !asset.value) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<AudioCue>>(`/api/control/v1/campaigns/${id}/audio-cues`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: name.value, asset_id: asset.value, kind: kind.value, loop: loop.value, default_volume: volume.value }) }); cues.value = [...cues.value, response.data]; revision.value++; name.value = ''; asset.value = ''; loop.value = false; volume.value = 100; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this audio cue.'; await load(); } finally { busy.value = false; } };
        onMounted(load); return { cues, assets, name, asset, kind, loop, volume, error, busy, create, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>Audio cues</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Add cue</h2><input v-model="name" maxlength="120" placeholder="Cue name" aria-label="Cue name"><select v-model="asset" aria-label="Audio asset"><option value="">Choose ready audio</option><option v-for="item in assets" :key="item.id" :value="item.id">{{ item.original_filename }}</option></select><select v-model="kind" aria-label="Cue type"><option value="music">Music</option><option value="sfx">Sound effect</option></select><label><input v-model="loop" type="checkbox"> Loop</label><label>Default volume <input v-model.number="volume" type="number" min="0" max="100"></label><button :disabled="busy" @click="create">{{ busy ? 'Creating…' : 'Create cue' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Draft cues</h2><p v-if="cues.length === 0" class="muted">No audio cues yet.</p><article v-for="cue in cues" :key="cue.id" class="asset"><div><strong>{{ cue.name }}</strong><div class="muted">{{ cue.kind }} · {{ cue.loop ? 'looping' : 'one shot' }} · {{ cue.default_volume }}%</div></div></article></section></main>`,
});

const VideoCuesView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter(); const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const cues = ref<VideoCue[]>([]); const videos = ref<Asset[]>([]); const scenes = ref<SceneRecord[]>([]); const name = ref(''); const primary = ref(''); const fallback = ref(''); const completion = ref<'restore_captured_scene' | 'enter_target_scene'>('restore_captured_scene'); const target = ref(''); const during = ref<'continue' | 'pause' | 'stop'>('pause'); const after = ref<'keep_current' | 'resume_prior' | 'start_target_default' | 'remain_silent'>('resume_prior'); const volume = ref(100); const muted = ref(false); const error = ref(''); const busy = ref(false);
        const load = async (): Promise<void> => { try { const [videoData, media, sceneData] = await Promise.all([api<ApiResponse<VideoCue[]>>(`/api/control/v1/campaigns/${id}/video-cues`), api<ApiResponse<Asset[]>>(`/api/control/v1/campaigns/${id}/assets`), api<ApiResponse<SceneRecord[]>>(`/api/control/v1/campaigns/${id}/scenes`)]); cues.value = videoData.data; videos.value = media.data.filter((item) => item.kind === 'video' && item.upload_status === 'ready'); scenes.value = sceneData.data; } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load video cues.'; } };
        const create = async (): Promise<void> => { if (!name.value.trim() || !primary.value || (completion.value === 'enter_target_scene' && !target.value)) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<VideoCue>>(`/api/control/v1/campaigns/${id}/video-cues`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: name.value, primary_asset_id: primary.value, fallback_asset_id: fallback.value || null, completion_mode: completion.value, target_scene_id: completion.value === 'enter_target_scene' ? target.value : null, music_during: during.value, music_after: after.value, embedded_audio_volume: volume.value, embedded_audio_muted: muted.value }) }); cues.value = [...cues.value, response.data]; revision.value++; name.value = ''; primary.value = ''; fallback.value = ''; target.value = ''; volume.value = 100; muted.value = false; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this video cue.'; await load(); } finally { busy.value = false; } };
        onMounted(load); return { cues, videos, scenes, name, primary, fallback, completion, target, during, after, volume, muted, error, busy, create, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>Video cues</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Add fullscreen video</h2><input v-model="name" maxlength="120" placeholder="Cue name" aria-label="Video cue name"><select v-model="primary" aria-label="Primary video"><option value="">Choose ready video</option><option v-for="asset in videos" :key="asset.id" :value="asset.id">{{ asset.original_filename }}</option></select><select v-model="fallback" aria-label="Fallback video"><option value="">No fallback</option><option v-for="asset in videos" :key="asset.id" :value="asset.id">{{ asset.original_filename }}</option></select><select v-model="completion" aria-label="Completion behavior"><option value="restore_captured_scene">Restore captured scene</option><option value="enter_target_scene">Enter target scene</option></select><select v-if="completion === 'enter_target_scene'" v-model="target" aria-label="Target scene"><option value="">Choose target scene</option><option v-for="scene in scenes" :key="scene.id" :value="scene.id">{{ scene.name }}</option></select><select v-model="during" aria-label="Music during video"><option value="continue">Continue scene music</option><option value="pause">Pause scene music</option><option value="stop">Stop scene music</option></select><select v-model="after" aria-label="Music after video"><option value="keep_current">Keep current music</option><option value="resume_prior">Resume prior music</option><option value="start_target_default">Start target default</option><option value="remain_silent">Remain silent</option></select><label>Embedded audio volume <input v-model.number="volume" type="number" min="0" max="100"></label><label><input v-model="muted" type="checkbox"> Mute embedded video audio</label><button :disabled="busy || !primary || !name.trim() || (completion === 'enter_target_scene' && !target)" @click="create">{{ busy ? 'Creating…' : 'Create video cue' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Draft video cues</h2><p v-if="cues.length === 0" class="muted">No video cues yet.</p><article v-for="cue in cues" :key="cue.id" class="asset"><div><strong>{{ cue.name }}</strong><div class="muted">{{ cue.completion_mode }} · music {{ cue.music_during }}/{{ cue.music_after }} · video audio {{ cue.embedded_audio_muted ? 'muted' : cue.embedded_audio_volume + '%' }}</div></div></article></section></main>`,
});

const ScenesView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter(); const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const scenes = ref<SceneRecord[]>([]); const images = ref<Asset[]>([]); const music = ref<AudioCue[]>([]); const presets = ref<StagePresetRecord[]>([]); const name = ref(''); const backdrop = ref(''); const cue = ref(''); const preset = ref(''); const transition = ref<'cut' | 'fade_black' | 'cross_dissolve'>('cut'); const duration = ref(0); const selected = ref(''); const alternates = ref<Array<{ id: string; name: string; asset_id: string }>>([]); const alternateName = ref(''); const alternateAsset = ref(''); const error = ref(''); const busy = ref(false);
        const loadAlternates = async (): Promise<void> => { if (!selected.value) { alternates.value = []; return; } alternates.value = (await api<ApiResponse<Array<{ id: string; name: string; asset_id: string }>>>(`/api/control/v1/campaigns/${id}/scenes/${selected.value}/backdrops`)).data; };
        const load = async (): Promise<void> => { try { const [sceneData, media, audio, stage] = await Promise.all([api<ApiResponse<SceneRecord[]>>(`/api/control/v1/campaigns/${id}/scenes`), api<ApiResponse<Asset[]>>(`/api/control/v1/campaigns/${id}/assets`), api<ApiResponse<AudioCue[]>>(`/api/control/v1/campaigns/${id}/audio-cues`), api<ApiResponse<StagePresetRecord[]>>(`/api/control/v1/campaigns/${id}/stage-presets`)]); scenes.value = sceneData.data; images.value = media.data.filter((item) => item.kind === 'image' && item.upload_status === 'ready'); music.value = audio.data.filter((item) => item.kind === 'music'); presets.value = stage.data; if (selected.value) await loadAlternates(); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load scenes.'; } };
        const create = async (): Promise<void> => { if (!name.value.trim()) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<SceneRecord>>(`/api/control/v1/campaigns/${id}/scenes`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: name.value, primary_backdrop_asset_id: backdrop.value || null, default_music_cue_id: cue.value || null, base_stage_preset_id: preset.value || null, transition: transition.value, transition_duration_ms: duration.value }) }); scenes.value = [...scenes.value, response.data]; revision.value++; name.value = ''; backdrop.value = ''; cue.value = ''; preset.value = ''; duration.value = 0; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this scene.'; await load(); } finally { busy.value = false; } };
        const addAlternate = async (): Promise<void> => { if (!selected.value || !alternateName.value.trim() || !alternateAsset.value) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<{ id: string; name: string; asset_id: string }>>(`/api/control/v1/campaigns/${id}/scenes/${selected.value}/backdrops`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: alternateName.value, asset_id: alternateAsset.value }) }); alternates.value = [...alternates.value, response.data]; revision.value++; alternateName.value = ''; alternateAsset.value = ''; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to add alternate backdrop.'; await loadAlternates(); } finally { busy.value = false; } };
        onMounted(load); return { scenes, images, music, presets, name, backdrop, cue, preset, transition, duration, selected, alternates, alternateName, alternateAsset, error, busy, create, addAlternate, loadAlternates, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>Scenes</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Add scene</h2><input v-model="name" maxlength="120" placeholder="Scene name" aria-label="Scene name"><select v-model="backdrop" aria-label="Primary backdrop"><option value="">No primary backdrop</option><option v-for="item in images" :key="item.id" :value="item.id">{{ item.original_filename }}</option></select><select v-model="cue" aria-label="Default music"><option value="">No default music</option><option v-for="item in music" :key="item.id" :value="item.id">{{ item.name }}</option></select><select v-model="preset" aria-label="Base stage preset"><option value="">Empty stage</option><option v-for="item in presets" :key="item.id" :value="item.id">{{ item.name }}</option></select><select v-model="transition" aria-label="Transition"><option value="cut">Cut</option><option value="fade_black">Fade through black</option><option value="cross_dissolve">Cross dissolve</option></select><label>Transition duration (ms) <input v-model.number="duration" type="number" min="0" max="30000"></label><button :disabled="busy" @click="create">{{ busy ? 'Creating…' : 'Create scene' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Alternate backdrops</h2><select v-model="selected" aria-label="Scene for alternate backdrops" @change="loadAlternates"><option value="">Choose scene</option><option v-for="scene in scenes" :key="scene.id" :value="scene.id">{{ scene.name }}</option></select><input v-model="alternateName" maxlength="120" placeholder="Backdrop name" aria-label="Alternate backdrop name"><select v-model="alternateAsset" aria-label="Alternate backdrop image"><option value="">Choose ready image</option><option v-for="item in images" :key="item.id" :value="item.id">{{ item.original_filename }}</option></select><button :disabled="busy || !selected" @click="addAlternate">Add alternate</button><article v-for="item in alternates" :key="item.id" class="asset"><strong>{{ item.name }}</strong></article></section><section class="panel stack"><h2>Draft scenes</h2><p v-if="scenes.length === 0" class="muted">No scenes yet.</p><article v-for="scene in scenes" :key="scene.id" class="asset"><div><strong>{{ scene.name }}</strong><div class="muted">{{ scene.transition }} · {{ scene.transition_duration_ms }}ms</div></div></article></section></main>`,
});

const DicePresetsView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter(); const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const presets = ref<DicePresetRecord[]>([]); const name = ref(''); const expression = ref(''); const visibility = ref<'public' | 'private'>('public'); const isDefault = ref(false); const error = ref(''); const busy = ref(false);
        const load = async (): Promise<void> => { try { presets.value = (await api<ApiResponse<DicePresetRecord[]>>(`/api/control/v1/campaigns/${id}/dice-presets`)).data; } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load dice presets.'; } };
        const create = async (): Promise<void> => { if (!name.value.trim() || !expression.value.trim()) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<DicePresetRecord>>(`/api/control/v1/campaigns/${id}/dice-presets`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, name: name.value, expression: expression.value, default_visibility: visibility.value, is_default: isDefault.value }) }); presets.value = [...presets.value.map((item) => ({ ...item, is_default: isDefault.value ? false : item.is_default })), response.data]; revision.value++; name.value = ''; expression.value = ''; isDefault.value = false; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this preset.'; await load(); } finally { busy.value = false; } };
        onMounted(load); return { presets, name, expression, visibility, isDefault, error, busy, create, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>Dice presets</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Add preset</h2><input v-model="name" maxlength="120" placeholder="Preset name" aria-label="Preset name"><input v-model="expression" maxlength="200" placeholder="4d6kh3 + 2" aria-label="Dice expression"><select v-model="visibility" aria-label="Default visibility"><option value="public">Public</option><option value="private">Private</option></select><label><input v-model="isDefault" type="checkbox"> Campaign default</label><button :disabled="busy" @click="create">{{ busy ? 'Creating…' : 'Create preset' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Draft presets</h2><p v-if="presets.length === 0" class="muted">No dice presets yet.</p><article v-for="preset in presets" :key="preset.id" class="asset"><div><strong>{{ preset.name }}</strong><div class="muted">{{ preset.expression }} · {{ preset.default_visibility }}{{ preset.is_default ? ' · default' : '' }}</div></div></article></section></main>`,
});

const SessionsView = defineComponent({
    components: { ControlMapStage, PresentationStage },
    setup() {
        const route = useRoute(); const router = useRouter(); const campaignId = String(route.params.campaign);
        const sessions = ref<LiveSessionRecord[]>([]); const revisions = ref<CampaignRevision[]>([]); const maps = ref<PinnedMap[]>([]); const scenes = ref<PinnedScene[]>([]); const sceneBackdrops = ref<PinnedSceneBackdrop[]>([]); const audioCues = ref<PinnedAudioCue[]>([]); const videoCues = ref<PinnedVideoCue[]>([]); const npcs = ref<PinnedNpc[]>([]); const npcStates = ref<PinnedNpcState[]>([]); const presets = ref<PinnedStagePreset[]>([]); const presetEntries = ref<PinnedStagePresetEntry[]>([]); const participants = ref<SessionParticipantRecord[]>([]); const npcReveals = ref<SessionNpcRevealRecord[]>([]); const selectedSessionId = ref(''); const createRevisionId = ref(''); const progressMode = ref<'fresh' | 'resume'>('fresh'); const playerMap = ref<PlayerMapState | null>(null); const progress = ref<MapProgress | null>(null); const presentation = ref<PresentationSnapshot | null>(null); const presentationAssetUrls = ref<Record<string, string>>({}); const standbySceneId = ref(''); const stagePresetId = ref(''); const stageNpcId = ref(''); const stageNpcStateId = ref(''); const brushMode = ref<'reveal' | 'hide'>('reveal'); const brushX = ref(.5); const brushY = ref(.5); const brushRadius = ref(.1); const imageUrl = ref(''); const error = ref(''); const busy = ref(false);
        const selectedSession = (): LiveSessionRecord | undefined => sessions.value.find((session) => session.id === selectedSessionId.value);
        const loadParticipants = async (): Promise<void> => { const session = selectedSession(); participants.value = session ? (await api<ApiResponse<SessionParticipantRecord[]>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/participants`)).data : []; };
        const loadNpcReveals = async (): Promise<void> => { const session = selectedSession(); npcReveals.value = session ? (await api<ApiResponse<SessionNpcRevealRecord[]>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/npc-reveals`)).data : []; };
        const selectedMap = (): PinnedMap | undefined => maps.value.find((map) => map.id === playerMap.value?.map_id);
        const resolveEntries = (entries: PresentationStateEntry[]): PresentationStageEntry[] => entries.flatMap((entry) => { const npc = npcs.value.find((item) => item.id === entry.npc_id); if (!npc) return []; const state = entry.npc_state_id ? npcStates.value.find((item) => item.id === entry.npc_state_id) : undefined; return [{ ...entry, name: npc.name, asset_id: state?.asset_id ?? npc.normal_asset_id, native_facing: npc.native_facing }]; });
        const activeEntries = computed(() => presentation.value ? resolveEntries(presentation.value.state.stage_entries) : []);
        const activeScene = computed(() => scenes.value.find((scene) => scene.id === presentation.value?.state.scene_id));
        const activeBackdrops = computed(() => { const scene = activeScene.value; if (!scene) return []; const primary = scene.primary_backdrop_asset_id ? [{ id: 'primary', asset_id: scene.primary_backdrop_asset_id, name: 'Primary backdrop' }] : []; return [...primary, ...sceneBackdrops.value.filter((backdrop) => backdrop.scene_id === scene.id)]; });
        const selectableNpcStates = computed(() => npcStates.value.filter((state) => state.npc_id === stageNpcId.value));
        const loadPresentationAssets = async (): Promise<void> => { const active = presentation.value?.state; if (!active) return; const assetIds = [active.backdrop_asset_id, ...activeEntries.value.map((entry) => entry.asset_id)].filter((assetId): assetId is string => assetId !== null && presentationAssetUrls.value[assetId] === undefined); const urls = await Promise.all(assetIds.map(async (assetId) => [assetId, (await api<ApiResponse<{ url: string }>>(`/api/control/v1/campaigns/${campaignId}/assets/${assetId}/read`)).data.url] as const)); presentationAssetUrls.value = { ...presentationAssetUrls.value, ...Object.fromEntries(urls) }; };
        const loadWorkspace = async (): Promise<void> => { const session = selectedSession(); if (!session) { maps.value = []; scenes.value = []; sceneBackdrops.value = []; audioCues.value = []; videoCues.value = []; npcs.value = []; npcStates.value = []; presets.value = []; presetEntries.value = []; playerMap.value = null; progress.value = null; presentation.value = null; presentationAssetUrls.value = {}; imageUrl.value = ''; return; } const [revision, state, presentationState] = await Promise.all([api<ApiResponse<{ manifest: { maps?: PinnedMap[]; scenes?: PinnedScene[]; scene_backdrops?: PinnedSceneBackdrop[]; audio_cues?: PinnedAudioCue[]; video_cues?: PinnedVideoCue[]; npcs?: PinnedNpc[]; npc_states?: PinnedNpcState[]; stage_presets?: PinnedStagePreset[]; stage_preset_entries?: PinnedStagePresetEntry[] } }>>(`/api/control/v1/campaigns/${campaignId}/revisions/${session.campaign_revision_id}`), api<ApiResponse<PlayerMapState>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/player-map`), api<ApiResponse<PresentationSnapshot>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/presentation-state`)]); maps.value = revision.data.manifest.maps ?? []; scenes.value = revision.data.manifest.scenes ?? []; sceneBackdrops.value = revision.data.manifest.scene_backdrops ?? []; audioCues.value = revision.data.manifest.audio_cues ?? []; videoCues.value = revision.data.manifest.video_cues ?? []; npcs.value = revision.data.manifest.npcs ?? []; npcStates.value = revision.data.manifest.npc_states ?? []; presets.value = revision.data.manifest.stage_presets ?? []; presetEntries.value = revision.data.manifest.stage_preset_entries ?? []; playerMap.value = state.data; presentation.value = presentationState.data; stagePresetId.value = presentationState.data.state.stage_preset_id ?? ''; presentationAssetUrls.value = {}; await loadPresentationAssets(); standbySceneId.value ||= scenes.value[0]?.id ?? ''; const map = selectedMap(); progress.value = state.data.map_id ? (await api<ApiResponse<MapProgress>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/maps/${state.data.map_id}/progress`)).data : null; imageUrl.value = map ? (await api<ApiResponse<{ url: string }>>(`/api/control/v1/campaigns/${campaignId}/assets/${map.image_asset_id}/read`)).data.url : ''; };
        const load = async (): Promise<void> => { try { const [sessionData, revisionData] = await Promise.all([api<ApiResponse<LiveSessionRecord[]>>(`/api/control/v1/campaigns/${campaignId}/sessions`), api<ApiResponse<CampaignRevision[]>>(`/api/control/v1/campaigns/${campaignId}/revisions`)]); sessions.value = sessionData.data; revisions.value = revisionData.data; createRevisionId.value ||= revisions.value[0]?.id ?? ''; selectedSessionId.value ||= sessions.value[0]?.id ?? ''; await loadWorkspace(); } catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = reason instanceof Error ? reason.message : 'Unable to load live sessions.'; } };
        const create = async (): Promise<void> => { if (!createRevisionId.value) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<LiveSessionRecord>>(`/api/control/v1/campaigns/${campaignId}/sessions`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), campaign_revision_id: createRevisionId.value, progress_mode: progressMode.value }) }); sessions.value = [response.data, ...sessions.value]; selectedSessionId.value = response.data.id; await loadWorkspace(); await loadNpcReveals(); } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to create this live session.'; } finally { busy.value = false; } };
        const setMap = async (mapId: string | null): Promise<void> => { const session = selectedSession(); if (!session || !playerMap.value) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<PlayerMapState>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/player-map`, { method: 'PUT', body: JSON.stringify({ command_id: commandId(), expected_revision: playerMap.value.revision, map_id: mapId }) }); playerMap.value = response.data; progress.value = mapId ? (await api<ApiResponse<MapProgress>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/maps/${mapId}/progress`)).data : null; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to update the Player map.'; await loadWorkspace(); } finally { busy.value = false; } };
        const selectMap = (event: Event): void => setMap((event.target as HTMLSelectElement).value || null);
        const brush = async (): Promise<void> => { const session = selectedSession(); const map = selectedMap(); if (!session || !map || !progress.value) return; busy.value = true; error.value = ''; try { progress.value = (await api<ApiResponse<MapProgress>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/maps/${map.id}/progress/fog`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: progress.value.revision, mode: brushMode.value, center_x: brushX.value, center_y: brushY.value, radius: brushRadius.value }) })).data; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to apply this fog brush.'; await loadWorkspace(); } finally { busy.value = false; } };
        const reset = async (): Promise<void> => { const session = selectedSession(); const map = selectedMap(); if (!session || !map || !progress.value || !window.confirm('Reset this map to its authored fog and token layout?')) return; busy.value = true; try { progress.value = (await api<ApiResponse<MapProgress>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/maps/${map.id}/progress/reset`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: progress.value.revision }) })).data; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to reset this map.'; await loadWorkspace(); } finally { busy.value = false; } };
        const saveTokens = async (): Promise<void> => { const session = selectedSession(); const map = selectedMap(); if (!session || !map || !progress.value) return; busy.value = true; try { progress.value = (await api<ApiResponse<MapProgress>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/maps/${map.id}/progress`, { method: 'PUT', body: JSON.stringify({ command_id: commandId(), expected_revision: progress.value.revision, tokens: progress.value.tokens.map(({ source_token_id, position_x, position_y, scale, sort_order }) => ({ source_token_id, position_x, position_y, scale, sort_order })) }) })).data; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to save token positions.'; await loadWorkspace(); } finally { busy.value = false; } };
        const brushAt = async (point: { x: number; y: number; mode: 'reveal' | 'hide'; radius: number }): Promise<void> => { brushX.value = point.x; brushY.value = point.y; brushMode.value = point.mode; brushRadius.value = point.radius; await brush(); };
        const moveTokens = async (tokens: MapToken[]): Promise<void> => { if (progress.value) progress.value.tokens = tokens; await saveTokens(); };
        const standby = async (): Promise<void> => { const session = selectedSession(); const scene = scenes.value.find((item) => item.id === standbySceneId.value); if (!session || !scene || !presentation.value) return; const stageEntries = scene.base_stage_preset_id ? presetEntries.value.filter((entry) => entry.stage_preset_id === scene.base_stage_preset_id).map(({ npc_id, npc_state_id, position_x, position_y, scale, layer_order, facing }) => ({ npc_id, npc_state_id, position_x, position_y, scale, layer_order, facing })) : []; const cue = audioCues.value.find((item) => item.id === scene.default_music_cue_id); const musicPlayback = cue ? { status: 'playing' as const, position_seconds: 0, position_command_id: null, loop: cue.loop, volume: cue.default_volume / 100, fade_duration_ms: 0 } : { status: 'stopped' as const, position_seconds: 0, position_command_id: null, loop: true, volume: 1, fade_duration_ms: 0 }; busy.value = true; try { presentation.value = (await api<ApiResponse<PresentationSnapshot>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/presentation-state/standby`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: presentation.value.revision, state: { scene_id: scene.id, backdrop_asset_id: scene.primary_backdrop_asset_id, music_cue_id: scene.default_music_cue_id, music_playback: musicPlayback, video_cue_id: null, stage_preset_id: scene.base_stage_preset_id, stage_entries: stageEntries } }) })).data; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to request standby.'; await loadWorkspace(); } finally { busy.value = false; } };
        const go = async (): Promise<void> => { const session = selectedSession(); if (!session || !presentation.value) return; busy.value = true; try { presentation.value = (await api<ApiResponse<PresentationSnapshot>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/presentation-state/go`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: presentation.value.revision }) })).data; await loadPresentationAssets(); } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to Go.'; await loadWorkspace(); } finally { busy.value = false; } };
        const savePresentationEntries = async (entries: PresentationStateEntry[], presetId = presentation.value?.state.stage_preset_id ?? null, backdropId = presentation.value?.state.backdrop_asset_id ?? null, musicCueId = presentation.value?.state.music_cue_id ?? null, videoCueId = presentation.value?.state.video_cue_id ?? null, musicPlayback = presentation.value?.state.music_playback, sfxMasterVolume = presentation.value?.state.sfx_master_volume ?? 1, sfxInstances = presentation.value?.state.sfx_instances ?? []): Promise<void> => { const session = selectedSession(); if (!session || !presentation.value) return; const state = presentation.value.state; busy.value = true; try { presentation.value = (await api<ApiResponse<PresentationSnapshot>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/presentation-state`, { method: 'PUT', body: JSON.stringify({ command_id: commandId(), expected_revision: presentation.value.revision, state: { scene_id: state.scene_id, backdrop_asset_id: backdropId, music_cue_id: musicCueId, music_playback: musicPlayback, sfx_master_volume: sfxMasterVolume, sfx_instances: sfxInstances, video_cue_id: videoCueId, stage_preset_id: presetId, stage_entries: entries } }) })).data; stagePresetId.value = presetId ?? ''; await loadPresentationAssets(); } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to update staged NPCs.'; await loadWorkspace(); } finally { busy.value = false; } };
        const movePresentationEntry = async (moved: PresentationStageEntry): Promise<void> => { if (!presentation.value) return; await savePresentationEntries(presentation.value.state.stage_entries.map((entry) => entry.npc_id === moved.npc_id && entry.npc_state_id === moved.npc_state_id && entry.layer_order === moved.layer_order ? { ...entry, position_x: moved.position_x, position_y: moved.position_y } : entry)); };
        const addPresentationNpc = async (): Promise<void> => { const npc = npcs.value.find((item) => item.id === stageNpcId.value); if (!npc || !presentation.value) return; const layerOrder = Math.max(-1, ...presentation.value.state.stage_entries.map((entry) => entry.layer_order)) + 1; await savePresentationEntries([...presentation.value.state.stage_entries, { npc_id: npc.id, npc_state_id: stageNpcStateId.value || null, position_x: .5, position_y: .85, scale: 1, layer_order: layerOrder, facing: npc.native_facing }]); };
        const removePresentationEntry = async (removed: PresentationStageEntry): Promise<void> => { if (!presentation.value) return; await savePresentationEntries(presentation.value.state.stage_entries.filter((entry) => !(entry.npc_id === removed.npc_id && entry.npc_state_id === removed.npc_state_id && entry.layer_order === removed.layer_order))); };
        const applyStagePreset = async (): Promise<void> => { if (!presentation.value) return; const entries = stagePresetId.value ? presetEntries.value.filter((entry) => entry.stage_preset_id === stagePresetId.value).map(({ npc_id, npc_state_id, position_x, position_y, scale, layer_order, facing }) => ({ npc_id, npc_state_id, position_x, position_y, scale, layer_order, facing })) : []; await savePresentationEntries(entries, stagePresetId.value || null); };
        const resetSceneStage = async (): Promise<void> => { const presetId = activeScene.value?.base_stage_preset_id ?? null; stagePresetId.value = presetId ?? ''; await applyStagePreset(); };
        const clearPresentationStage = async (): Promise<void> => { stagePresetId.value = ''; await savePresentationEntries([], null); };
        const setBackdrop = async (assetId: string): Promise<void> => { if (!presentation.value) return; await savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, assetId || null); };
        const selectBackdrop = (event: Event): void => { void setBackdrop((event.target as HTMLSelectElement).value); };
        const selectMusic = (event: Event): void => { if (!presentation.value) return; const cue = audioCues.value.find((item) => item.id === (event.target as HTMLSelectElement).value); const playback = cue ? { status: 'playing' as const, position_seconds: 0, position_command_id: null, loop: cue.loop, volume: cue.default_volume / 100, fade_duration_ms: 0 } : { status: 'stopped' as const, position_seconds: 0, position_command_id: null, loop: true, volume: 1, fade_duration_ms: 0 }; void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, cue?.id ?? null, presentation.value.state.video_cue_id, playback); };
        const saveMusicPlayback = (next: Partial<MusicPlayback>): void => { if (!presentation.value || !presentation.value.state.music_cue_id) return; void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, presentation.value.state.video_cue_id, { ...presentation.value.state.music_playback, ...next }); };
        const setMusicVolume = (event: Event): void => saveMusicPlayback({ volume: Number((event.target as HTMLInputElement).value) / 100 });
        const seekMusic = (positionSeconds: number): void => saveMusicPlayback({ position_seconds: positionSeconds, position_command_id: crypto.randomUUID() });
        const setMusicPosition = (event: Event): void => seekMusic(Number((event.target as HTMLInputElement).value));
        const setMusicLoop = (event: Event): void => saveMusicPlayback({ loop: (event.target as HTMLInputElement).checked });
        const setMusicFade = (event: Event): void => saveMusicPlayback({ fade_duration_ms: Number((event.target as HTMLInputElement).value) });
        const triggerSfx = (cueId: string): void => { if (!presentation.value) return; const cue = audioCues.value.find((item) => item.id === cueId); if (!cue) return; const instance: SfxInstance = { id: crypto.randomUUID(), cue_id: cue.id, loop: cue.loop, volume: cue.default_volume / 100 }; void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, presentation.value.state.video_cue_id, presentation.value.state.music_playback, presentation.value.state.sfx_master_volume ?? 1, [...(presentation.value.state.sfx_instances ?? []), instance]); };
        const stopSfx = (instanceId: string): void => { if (!presentation.value) return; void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, presentation.value.state.video_cue_id, presentation.value.state.music_playback, presentation.value.state.sfx_master_volume ?? 1, (presentation.value.state.sfx_instances ?? []).filter((instance) => instance.id !== instanceId)); };
        const stopAllSfx = (): void => { if (!presentation.value) return; void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, presentation.value.state.video_cue_id, presentation.value.state.music_playback, presentation.value.state.sfx_master_volume ?? 1, []); };
        const setSfxMasterVolume = (event: Event): void => { if (!presentation.value) return; void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, presentation.value.state.video_cue_id, presentation.value.state.music_playback, Number((event.target as HTMLInputElement).value) / 100, presentation.value.state.sfx_instances ?? []); };
        const releaseClaim = async (participant: SessionParticipantRecord): Promise<void> => { const session = selectedSession(); if (!session) return; busy.value = true; try { await api(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/participants/${participant.id}/claim`, { method: 'DELETE' }); await loadParticipants(); } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to release the character claim.'; } finally { busy.value = false; } };
        const revokeParticipant = async (participant: SessionParticipantRecord): Promise<void> => { const session = selectedSession(); if (!session || !window.confirm(`Revoke ${participant.display_name} from this session?`)) return; busy.value = true; try { await api(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/participants/${participant.id}`, { method: 'DELETE' }); await loadParticipants(); } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to revoke this participant.'; } finally { busy.value = false; } };
        const npcIsRevealed = (npcId: string): boolean => npcReveals.value.some((reveal) => reveal.npc_id === npcId && reveal.is_revealed);
        const setNpcReveal = async (npcId: string, isRevealed: boolean): Promise<void> => { const session = selectedSession(); if (!session) return; busy.value = true; error.value = ''; try { const response = await api<ApiResponse<SessionNpcRevealRecord>>(`/api/control/v1/campaigns/${campaignId}/sessions/${session.id}/npc-reveals/${npcId}`, { method: 'PUT', body: JSON.stringify({ command_id: commandId(), is_revealed: isRevealed }) }); npcReveals.value = [...npcReveals.value.filter((reveal) => reveal.npc_id !== npcId), response.data]; } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to update this NPC reveal.'; await loadNpcReveals(); } finally { busy.value = false; } };
        const selectVideo = (event: Event): void => { if (presentation.value) void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, (event.target as HTMLSelectElement).value || null); };
        const abortVideo = (): void => { if (presentation.value) void savePresentationEntries(presentation.value.state.stage_entries, presentation.value.state.stage_preset_id, presentation.value.state.backdrop_asset_id, presentation.value.state.music_cue_id, null); };
        onMounted(async () => { await load(); await loadParticipants(); await loadNpcReveals(); }); return { sessions, revisions, maps, scenes, audioCues, videoCues, npcs, presets, participants, selectedSessionId, createRevisionId, progressMode, playerMap, progress, presentation, presentationAssetUrls, activeEntries, activeScene, activeBackdrops, selectableNpcStates, standbySceneId, stagePresetId, stageNpcId, stageNpcStateId, brushMode, brushX, brushY, brushRadius, imageUrl, error, busy, selectedMap, loadWorkspace, loadParticipants, loadNpcReveals, create, setMap, selectMap, brush, brushAt, reset, saveTokens, moveTokens, standby, go, movePresentationEntry, addPresentationNpc, removePresentationEntry, applyStagePreset, resetSceneStage, clearPresentationStage, setBackdrop, selectBackdrop, selectMusic, saveMusicPlayback, seekMusic, setMusicVolume, setMusicPosition, setMusicLoop, setMusicFade, triggerSfx, stopSfx, stopAllSfx, setSfxMasterVolume, releaseClaim, revokeParticipant, npcIsRevealed, setNpcReveal, selectVideo, abortVideo, back: () => router.push('/') };
    },
    template: `<main class="shell stack">
        <header class="row"><div><div class="eyebrow">Live session</div><h1>Maps and fog</h1></div><button class="secondary" @click="back">Campaigns</button></header>
        <p v-if="error" class="error" role="alert">{{ error }}</p>
        <section v-if="presentation" class="panel stack"><h2>Scene music</h2><select :value="presentation.state.music_cue_id || ''" aria-label="Scene music" @change="selectMusic"><option value="">Stop music</option><option v-for="cue in audioCues.filter((cue) => cue.kind === 'music')" :key="cue.id" :value="cue.id">{{ cue.name }}</option></select><template v-if="presentation.state.music_cue_id"><div class="row"><button class="secondary" :disabled="busy" @click="saveMusicPlayback({ status: 'playing' })">Play</button><button class="secondary" :disabled="busy" @click="saveMusicPlayback({ status: 'paused' })">Pause</button><button class="secondary" :disabled="busy" @click="seekMusic(0)">Restart</button><button class="danger" :disabled="busy" @click="saveMusicPlayback({ status: 'stopped', position_seconds: 0 })">Stop</button></div><div class="row"><label>Seek (seconds) <input :value="presentation.state.music_playback.position_seconds" type="number" min="0" step=".1" @change="setMusicPosition"></label><label>Volume (%) <input :value="Math.round(presentation.state.music_playback.volume * 100)" type="number" min="0" max="100" @change="setMusicVolume"></label><label>Fade (ms) <input :value="presentation.state.music_playback.fade_duration_ms" type="number" min="0" max="30000" step="100" @change="setMusicFade"></label><label><input :checked="presentation.state.music_playback.loop" type="checkbox" @change="setMusicLoop"> Loop</label></div></template></section>
        <section v-if="presentation" class="panel stack"><header class="row"><h2>Sound effects</h2><button class="danger" :disabled="busy || !(presentation.state.sfx_instances || []).length" @click="stopAllSfx">Stop all</button></header><div class="row"><label>Master volume (%) <input :value="Math.round((presentation.state.sfx_master_volume ?? 1) * 100)" type="number" min="0" max="100" @change="setSfxMasterVolume"></label></div><div class="row"><button v-for="cue in audioCues.filter((cue) => cue.kind === 'sfx')" :key="cue.id" :disabled="busy" @click="triggerSfx(cue.id)">Play {{ cue.name }}</button></div><p v-if="audioCues.filter((cue) => cue.kind === 'sfx').length === 0" class="muted">No sound effects are pinned to this session.</p><article v-for="instance in presentation.state.sfx_instances || []" :key="instance.id" class="asset"><div><strong>{{ audioCues.find((cue) => cue.id === instance.cue_id)?.name || 'Sound effect' }}</strong><div class="muted">{{ instance.loop ? 'Looping' : 'One shot' }} · {{ Math.round(instance.volume * 100) }}%</div></div><button class="danger" :disabled="busy" @click="stopSfx(instance.id)">Stop</button></article></section>
        <section v-if="presentation" class="panel stack"><h2>Fullscreen video</h2><p class="muted">Starting a cue captures the current scene. Abort restores that captured scene.</p><select :value="presentation.state.video_cue_id || ''" aria-label="Fullscreen video" @change="selectVideo"><option value="">No active video</option><option v-for="cue in videoCues" :key="cue.id" :value="cue.id">{{ cue.name }} · {{ cue.completion_mode }} · music {{ cue.music_during }}/{{ cue.music_after }}</option></select><button v-if="presentation.state.video_cue_id" class="danger" :disabled="busy" @click="abortVideo">Abort video and restore scene</button></section>
        <section class="panel stack"><h2>Start a session</h2><select v-model="createRevisionId" aria-label="Published revision"><option value="">Choose a published revision</option><option v-for="revision in revisions" :key="revision.id" :value="revision.id">Revision {{ revision.number }}</option></select><select v-model="progressMode" aria-label="Progress mode"><option value="fresh">Fresh progress</option><option value="resume">Resume progress</option></select><button :disabled="busy || !createRevisionId" @click="create">Start session</button></section>
        <section class="panel stack"><h2>Active session</h2><select v-model="selectedSessionId" aria-label="Live session" @change="loadWorkspace(); loadParticipants(); loadNpcReveals()"><option value="">Choose session</option><option v-for="session in sessions" :key="session.id" :value="session.id">{{ session.player_code }} · {{ session.status }}</option></select><template v-if="playerMap"><div class="row"><select :value="playerMap.map_id || ''" aria-label="Current Player map" @change="selectMap"><option value="">Hide Player map</option><option v-for="map in maps" :key="map.id" :value="map.id">{{ map.name }}</option></select><button class="secondary" :disabled="busy" @click="setMap(null)">Hide map</button></div><p v-if="!playerMap.map_id" class="muted">No map is currently shared with Players or Spectators.</p></template></section>
        <section v-if="selectedSessionId" class="panel stack"><h2>Participants</h2><p v-if="participants.length === 0" class="muted">No participants have joined this session.</p><article v-for="participant in participants" :key="participant.id" class="asset"><div><strong>{{ participant.display_name }}</strong><div class="muted">{{ participant.role }}{{ participant.player_character_id ? ' · character claimed' : '' }}{{ participant.revoked_at ? ' · revoked' : '' }}</div></div><div class="row"><button v-if="participant.player_character_id && !participant.revoked_at" class="secondary" :disabled="busy" @click="releaseClaim(participant)">Release claim</button><button v-if="!participant.revoked_at" class="danger" :disabled="busy" @click="revokeParticipant(participant)">Revoke</button></div></article></section>
        <section v-if="selectedSessionId" class="panel stack"><h2>NPC profiles</h2><p class="muted">Presentation staging never reveals a profile. Choose exactly what Players and Spectators can read.</p><p v-if="npcs.length === 0" class="muted">No NPCs are pinned to this session.</p><article v-for="npc in npcs" :key="npc.id" class="asset"><div><strong>{{ npc.name }}</strong><div class="muted">{{ npcIsRevealed(npc.id) ? 'Revealed to participants' : 'Hidden from participants' }}</div></div><button v-if="npcIsRevealed(npc.id)" class="danger" :disabled="busy" @click="setNpcReveal(npc.id, false)">Hide profile</button><button v-else :disabled="busy" @click="setNpcReveal(npc.id, true)">Reveal profile</button></article></section>
        <section v-if="presentation" class="panel stack"><h2>Presentation preview</h2><p class="muted">Drag a staged NPC to reposition it. Every edit saves as a revisioned active-stage update.</p><PresentationStage :backdrop-asset-id="presentation.state.backdrop_asset_id" :transition="activeScene?.transition || 'cut'" :transition-duration-ms="activeScene?.transition_duration_ms || 0" :stage-tween-duration-ms="presets.find((preset) => preset.id === presentation.state.stage_preset_id)?.tween_duration_ms || 0" :stage-tween-easing="presets.find((preset) => preset.id === presentation.state.stage_preset_id)?.tween_easing || 'linear'" :entries="activeEntries" :asset-urls="presentationAssetUrls" editable @move-entry="movePresentationEntry" /><div class="row"><select :value="presentation.state.backdrop_asset_id || ''" aria-label="Scene backdrop" @change="selectBackdrop"><option value="">No backdrop</option><option v-for="backdrop in activeBackdrops" :key="backdrop.id" :value="backdrop.asset_id">{{ backdrop.name }}</option></select><button class="secondary" :disabled="busy || !activeScene" @click="setBackdrop(activeScene.primary_backdrop_asset_id || '')">Use primary backdrop</button></div><div class="row"><button class="secondary" :disabled="busy || !activeScene" @click="resetSceneStage">Reset scene stage</button><button class="danger" :disabled="busy" @click="clearPresentationStage">Clear stage</button></div><div class="row"><select v-model="stagePresetId" aria-label="Stage preset"><option value="">Empty stage</option><option v-for="preset in presets" :key="preset.id" :value="preset.id">{{ preset.name }}</option></select><button :disabled="busy" @click="applyStagePreset">Apply preset</button></div><div class="row"><select v-model="stageNpcId" aria-label="NPC to stage" @change="stageNpcStateId = ''"><option value="">Add an NPC</option><option v-for="npc in npcs" :key="npc.id" :value="npc.id">{{ npc.name }}</option></select><select v-model="stageNpcStateId" aria-label="NPC state"><option value="">Normal appearance</option><option v-for="state in selectableNpcStates" :key="state.id" :value="state.id">{{ state.name }}</option></select><button :disabled="busy || !stageNpcId" @click="addPresentationNpc">Add to stage</button></div><article v-for="entry in activeEntries" :key="entry.npc_id + ':' + entry.npc_state_id + ':' + entry.layer_order" class="asset"><strong>{{ entry.name }}</strong><span class="muted">Layer {{ entry.layer_order + 1 }}</span><button class="danger" :disabled="busy" @click="removePresentationEntry(entry)">Remove</button></article></section>
        <section v-if="presentation" class="panel stack"><h2>Presentation standby</h2><p class="muted">Live scene: {{ presentation.state.scene_id || 'None' }} · Standby: {{ presentation.state.standby_status }}{{ presentation.state.standby_error ? ' — ' + presentation.state.standby_error : '' }}</p><div class="row"><select v-model="standbySceneId" aria-label="Standby scene"><option value="">Choose scene</option><option v-for="scene in scenes" :key="scene.id" :value="scene.id">{{ scene.name }}</option></select><button :disabled="busy || !standbySceneId" @click="standby">Standby</button><button :disabled="busy || presentation.state.standby_status !== 'ready'" @click="go">Go</button></div></section>
        <section v-if="progress && selectedMap()" class="panel stack"><header class="row"><div><h2>{{ selectedMap()?.name }}</h2><p class="muted">Map revision {{ progress.revision }} · {{ progress.fog.brushes.length }} live brush operations</p></div><button class="danger" :disabled="busy" @click="reset">Reset map</button></header><ControlMapStage :image-url="imageUrl" :tokens="progress.tokens" :brush-mode="brushMode" :brush-radius="brushRadius" @brush="brushAt" @move-tokens="moveTokens" /><div class="row"><select v-model="brushMode" aria-label="Fog brush mode"><option value="reveal">Reveal fog</option><option value="hide">Hide with fog</option></select><label>X <input v-model.number="brushX" type="number" min="0" max="1" step=".01"></label><label>Y <input v-model.number="brushY" type="number" min="0" max="1" step=".01"></label><label>Radius <input v-model.number="brushRadius" type="number" min=".005" max="1" step=".01"></label><button :disabled="busy" @click="brush">Apply brush</button></div><section class="stack"><h3>Token positions</h3><article v-for="token in progress.tokens" :key="token.source_token_id" class="asset"><strong>{{ token.label || token.source_token_id }}</strong><label>X <input v-model.number="token.position_x" type="number" min="0" max="1" step=".01"></label><label>Y <input v-model.number="token.position_y" type="number" min="0" max="1" step=".01"></label><label>Scale <input v-model.number="token.scale" type="number" min=".1" max="5" step=".1"></label></article><button :disabled="busy" @click="saveTokens">Save token positions</button></section></section>
    </main>`,
});

const AssetsView = defineComponent({
    setup() {
        const route = useRoute(); const router = useRouter();
        const id = String(route.params.campaign); const revision = ref(Number(route.query.revision ?? 1));
        const assets = ref<Asset[]>([]); const file = ref<File | null>(null); const error = ref(''); const busy = ref(false);
        const load = async (): Promise<void> => {
            try { assets.value = (await api<ApiResponse<Asset[]>>(`/api/control/v1/campaigns/${id}/assets`)).data; }
            catch (reason) { if (reason instanceof ApiError && reason.status === 401) await router.replace('/login'); else error.value = 'Unable to load this asset library.'; }
        };
        const choose = (event: Event): void => { file.value = (event.target as HTMLInputElement).files?.[0] ?? null; };
        const kindFor = (mime: string): 'image' | 'audio' | 'video' | null => mime.startsWith('image/') ? 'image' : mime.startsWith('audio/') ? 'audio' : mime.startsWith('video/') ? 'video' : null;
        const upload = async (): Promise<void> => {
            if (!file.value) return; const selected = file.value; const kind = kindFor(selected.type); if (!kind) { error.value = 'Choose a supported image, audio, or video file.'; return; }
            busy.value = true; error.value = '';
            try {
                const start = await api<ApiResponse<Asset> & { upload: { part_size: number; parts: Array<{ number: number; url: string }> } }>(`/api/control/v1/campaigns/${id}/assets/uploads`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value, original_filename: selected.name, kind, declared_mime: selected.type, byte_size: selected.size }) });
                const parts = await Promise.all(start.upload.parts.map(async (part) => {
                    const body = selected.slice((part.number - 1) * start.upload.part_size, Math.min(part.number * start.upload.part_size, selected.size));
                    const response = await fetch(part.url, { method: 'PUT', body }); const eTag = response.headers.get('ETag'); if (!response.ok || !eTag) throw new Error('A storage upload part failed.'); return { number: part.number, e_tag: eTag };
                }));
                const done = await api<ApiResponse<Asset>>(`/api/control/v1/campaigns/${id}/assets/${start.data.id}/complete`, { method: 'POST', body: JSON.stringify({ command_id: commandId(), expected_revision: revision.value + 1, parts }) });
                revision.value += 2; assets.value = [done.data, ...assets.value.filter((asset) => asset.id !== done.data.id)]; file.value = null;
            } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Unable to upload this asset.'; await load(); } finally { busy.value = false; }
        };
        const open = async (asset: Asset): Promise<void> => { try { window.open((await api<ApiResponse<{ url: string }>>(`/api/control/v1/campaigns/${id}/assets/${asset.id}/read`)).data.url, '_blank', 'noopener'); } catch { error.value = 'This asset is not ready to open.'; } };
        onMounted(load); return { assets, file, error, busy, choose, upload, open, back: () => router.push('/') };
    },
    template: `<main class="shell stack"><header class="row"><div><div class="eyebrow">Campaign draft</div><h1>Asset library</h1></div><button class="secondary" @click="back">Campaigns</button></header><section class="panel stack"><h2>Upload media</h2><p class="muted">Images, audio, and video upload directly to private storage and are validated before use.</p><input aria-label="Asset file" type="file" accept="image/jpeg,image/png,image/webp,audio/mpeg,audio/wav,audio/ogg,video/mp4,video/webm" @change="choose"><button :disabled="!file || busy" @click="upload">{{ busy ? 'Uploading…' : 'Upload asset' }}</button></section><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel stack"><h2>Private assets</h2><p v-if="assets.length === 0" class="muted">No assets uploaded yet.</p><article v-for="asset in assets" :key="asset.id" class="asset"><div><strong>{{ asset.original_filename }}</strong><div class="muted">{{ asset.kind }} · {{ asset.upload_status }}</div><div v-if="asset.validation_error" class="error">{{ asset.validation_error }}</div></div><button v-if="asset.upload_status === 'ready'" class="secondary" @click="open(asset)">Open</button></article></section></main>`,
});

const router = createRouter({
    history: createWebHistory('/control'),
    routes: [
        { path: '/', component: CampaignsView },
        { path: '/campaigns/:campaign/assets', component: AssetsView },
        { path: '/campaigns/:campaign/pcs', component: PlayerCharactersView },
        { path: '/campaigns/:campaign/npcs', component: NpcsView },
        { path: '/campaigns/:campaign/audio', component: AudioCuesView },
        { path: '/campaigns/:campaign/video', component: VideoCuesView },
        { path: '/campaigns/:campaign/scenes', component: ScenesView },
        { path: '/campaigns/:campaign/dice', component: DicePresetsView },
        { path: '/campaigns/:campaign/sessions', component: SessionsView },
        { path: '/login', component: LoginView },
    ],
});

createApp({ template: '<RouterView />' }).use(createPinia()).use(router).use(VueKonva).mount('#app');
